export enum StyleType {
    camera = "camera",
    local = "local",
    cartFiled = "cartFiled",
    chat = "chat",
    search = "search",
    arrowUp = "arrowUp",
    arrowDown = "arrowDown",
    view = "view",
    arrowRight = "arrowRight",
    cartEmpty = "cartEmpty",
    edit = "edit",
    arrowRightSmall = "arrowRightSmall",
    arrowLeftSmall = "arrowLeftSmall",
    arrowRightBold = "arrowRightBold",
  }